language: cpp

os:
  - linux
  - osx

dist: xenial
osx_image: xcode9

compiler:
  - g++
  - clang

cache:
  - ccache: true
  - pip

addons:
  apt:
    sources:
      # sources list: https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json
      - ubuntu-toolchain-r-test
    packages:
      # packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
      - g++-5
      - clang-4.0


install:
  - CXXFLAGS="$CXXFLAGS -Wno-unknown-attributes"
  - |
    if [ "$CXX" = "clang++" ]; then
      CXXFLAGS="$CXXFLAGS -Qunused-arguments"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update > /dev/null
      brew install ccache meson

      # ccache
      PATH="/usr/local/opt/ccache/libexec:$PATH"
    else
      if [ "$CXX" = "g++" ]; then
        CXX="ccache g++-5"
      else
        CXX="ccache clang++-4.0"
      fi

      # python
      pyenv versions
      pyenv global 3.6
      python3 --version

      # python-pip
      pip3 --version

      # meson
      pip3 install --user meson

      # ninja
      mkdir ~/ninja
      wget "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip" -O ~/ninja/ninja-linux.zip
      unzip ~/ninja/ninja-linux.zip -d ~/ninja
      PATH="$PATH":~/ninja
      ninja --version
    fi


script:
  # tests
  - cd "$TRAVIS_BUILD_DIR/tests"
  - CXXFLAGS="$CXXFLAGS" meson "_build"
  - cd "_build" && ninja -j1
  - ./run_tests -d yes
  # program
  - cd "$TRAVIS_BUILD_DIR/src/program"
  - CXXFLAGS="$CXXFLAGS" meson "_build"
  - cd "_build" && ninja -j1
